# JWT authentication
GET http://localhost:3000/userData
Authorization: bearer-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzaXIgS2hhbiIsImlhdCI6MTczODk1MzIyNywiZXhwIjoxNzM4OTU2ODI3fQ.Bogk6xaOhEooYobd3uOw5xbfwirnkqnH6m172v7b7dY

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"Yasir Khan"
}

###
POST  http://localhost:4000/write-user-data
Content-Type: application/json

{
    "name":"yasir khan",
    "email":"random2@email.com",
    "password":"random"
}







###
POST  http://localhost:4007/login
Content-Type: application/json

{
    "email":"random2@email.com",
    "password":"random"
}
###


POST  http://localhost:4007/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2E3NTljOTdiMjQwZTQ1Mjc2YmJhMGEiLCJpYXQiOjE3MzkwMzc2NzcsImV4cCI6MTczOTY0MjQ3N30.5UFo5dCjuxbo0tO_puM2LTw6ERuVRjIhoN2_vvhDha4"
}

###










# GET http://localhost:3000

# ####

# POST http://localhost:3000/users-write
# Content-Type: application/json

# {
#   "name": "yasir",
#   "password":"random"
# }
# ###

# POST http://localhost:3000/user/login
# Content-Type: application/json

# {
#   "name": "yasi2r",
#   "password":"random"
# }
